#!/bin/bash

# Determine config path
if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

MPV_CHANNEL_SELECTOR_CONFIG_DIR="$XDG_CONFIG_HOME/mpv-channel-selector"
if [ ! -d "$DIRECTORY" ]; then 
    mkdir -p "$MPV_CHANNEL_SELECTOR_CONFIG_DIR"
fi

CHANNEL_LIST_PATH="$MPV_CHANNEL_SELECTOR_CONFIG_DIR/channel-list"
# Create config file if it doesn't exist
if [ ! -f "$CHANNEL_LIST_PATH" ]; then
    touch "$CHANNEL_LIST_PATH"
fi

HDHOMERUN_IP_PATH="$MPV_CHANNEL_SELECTOR_CONFIG_DIR/hdhomerun-ip"
if [ -f "$HDHOMERUN_IP_PATH" ]; then
    read -r HDHOMERUN_IP < "$HDHOMERUN_IP_PATH"
fi

if [ -z "${HDHOMERUN_IP}" ]; then
    echo -n "Enter the IP address of the HDHomeRun: "
    read HDHOMERUN_IP
    echo "${HDHOMERUN_IP}" >> $HDHOMERUN_IP_PATH
fi

# Define an array to store the COMMANDS
COMMANDS=()

OPTION_NUMBER=1
LAST_OPTION=$OPTION_NUMBER
while IFS='=' read -r NAME COMMAND
do
    echo "$OPTION_NUMBER.) $NAME"
    COMMANDS+=("$COMMAND")
    ((OPTION_NUMBER+=1))
    LAST_OPTION=$OPTION_NUMBER
done < $CHANNEL_LIST_PATH

ADD_CHANNEL_OPTION=$OPTION_NUMBER
echo "$ADD_CHANNEL_OPTION.) Add new channel"
((OPTION_NUMBER+=1))

RESET_CONFIGS_OPTION=$OPTION_NUMBER
echo "$RESET_CONFIGS_OPTION.) Reset configs"

read -p "Select a channel or option: " USER_INPUT

# Handle user selection
if (( USER_INPUT == ADD_CHANNEL_OPTION ))
then
    echo "Creating new channel entry..."
    echo -n "Enter an alias for the channel: "
    read user_channel_alias
    echo -n "Enter a channel number: "
    read user_channel_num

    # Store the entry in the config file.
    echo "${user_channel_alias}=mpv http://${HDHOMERUN_IP}:5004/auto/v${user_channel_num} -fs --deinterlace" >> ${CHANNEL_LIST_PATH}

    # Sort the file alphabetically now that there's a new entry.
    sort -o ${CHANNEL_LIST_PATH} ${CHANNEL_LIST_PATH}
elif (( USER_INPUT == RESET_CONFIGS_OPTION ))
then
    echo "You are about to remove $MPV_CHANNEL_SELECTOR_CONFIG_DIR."
    read -p "Do you want to proceed? (y/n): " RESPONSE
    if [[ "$RESPONSE" == "y" ]]; then
        rm -r $MPV_CHANNEL_SELECTOR_CONFIG_DIR
    else
        echo "Aborting..."
    fi
elif (( USER_INPUT < LAST_OPTION ))
then
    echo "Opening channel..."
    ${COMMANDS[$USER_INPUT - 1]}
else
    echo "Invalid selection!"
fi

